version: 1

formatters:
    simple:
        format: "%(name)s - %(lineno)d -  %(message)s"

    complex:
        format: "%(asctime)s - %(name)s - %(lineno)d -  %(message)s"


handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple

    file:
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        backupCount: 5
        level: DEBUG
        formatter: complex
        filename : CricHQ.log

loggers:

    VMixExample:
        level: INFO
        handlers: [console]
        propagate: yes

    vMix:
        level: DEBUG
        handlers: [console]
        propagate: yes

    vMix:
        level: DEBUG
        handlers: [console, file]
        propagate: yes

    __main__:   
        level: DEBUG
        handlers: [console, file]
        propagate: yes
        